setting: RL_IDM

configuration:
  cruise_IDM:
    file: "stats/New/Cruise/No-Time-Budget/mpc_car_acado_data_1_goals.txt"
    v_des: 15
    weights: [0, 6500]

  HSRL_IDM:
    file: "stats/New/HighSpeed_RightLane/No-Time-Budget/mpc_car_acado_data_1_goals.txt"
    v_des: 20
    weights: [50, 100]
  

  RL_IDM:
    file: "stats/New/RightLane/No-Time-Budget/mpc_car_acado_data_1_goals.txt"
    v_des: 15
    weights: [50, 0]
  
  
  cruise_NGSIM:
    file: "stats/New/NGSIM/No-Time-Budget/cruise/mpc_car_acado_data_1_goals.txt"
    v_des: 15
    weights: [0, 6500]

  HSRL_NGSIM:
    file: "stats/New/NGSIM/No-Time-Budget/hsrl/mpc_car_acado_data_1_goals.txt"
    v_des: 20
    weights: [50, 100]



